# Development Docker Compose - Simplified version for testing
services:
  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flipdocs-network

  # API Service (ElysiaJS with Bun) - Development mode
  api:
    image: oven/bun:1
    working_dir: /app
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env.local
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - flipdocs-network
    command: ["sh", "-c", "cd /app && bun install && bun --watch apps/api/src/index.ts"]

  # Web Service (Next.js) - Development mode
  web:
    image: oven/bun:1
    working_dir: /app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - PORT=3000
    volumes:
      - .:/app
    depends_on:
      - api
    networks:
      - flipdocs-network
    command: ["sh", "-c", "cd /app && bun install && cd apps/web && bun run dev"]

  # Nginx (Development proxy) - Optional
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
      - api
    networks:
      - flipdocs-network
    profiles:
      - proxy

volumes:
  redis_data:

networks:
  flipdocs-network:
    driver: bridge