name: flipdocs
services:
  api:
    image: ${REGISTRY}/${API_IMAGE}
    container_name: flipdocs-api
    volumes:
      - ./data/storage:/app/storage
    environment:
      - TZ=UTC
      - PORT=3001
      - NODE_ENV=production
      # Clerk Configuration
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      # Supabase Configuration (API uses different names)
      - SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      # CORS Configuration
      - FRONTEND_URL=http://web:3000
    restart: unless-stopped

  web:
    image: ${REGISTRY}/${WEB_IMAGE}
    container_name: flipdocs-web
    environment:
      - NODE_ENV=production
      # API Configuration - Use env variable for external access
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      # Clerk Configuration (both public and secret needed)
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      # Supabase Configuration (both prefixed and non-prefixed needed)
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: flipdocs-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${PORT:-80}:80
    depends_on:
      - web
      - api
    restart: unless-stopped