"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";
import Sidebar from "./components/sidebar/sidebar";
import { RootProvider } from "./components/providers/root-provider";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAuthPage = pathname.startsWith("/sign-in");
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header> */}
          {isAuthPage ? (
            <div className="flex justify-center items-center h-screen">{children}</div>
          ) : (
            <RootProvider>
              <div className="flex w-full h-screen">
                <div className="overflow-y-auto dark:bg-secondary-foreground w-[220px] border">
                  <Sidebar />
                </div>
                <div className="w-0 flex-grow h-full flex flex-col border ">
                  {/* Top Header */}
                  {/* <Header /> */}
                  <div className="flex-grow w-full h-0 overflow-auto">{children}</div>
                </div>
              </div>
            </RootProvider>
          )}
        </body>
      </html>
    </ClerkProvider>
  );
}
